# Generated by Django 4.2.20 on 2025-03-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descirption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='pric',
            new_name='price',
        ),
    ]
